### ISSUE TITLE
Reading from strings causes segmentation fault

### ISSUE THREAD

**Issue by aaronryank** [aaronryank/rubiks-cube#12]
This is due to `getwc` trying to read a multibyte char from a string that was `fmemopen`'ed from a single-byte string.

Possible fixes:

 - Find or implement a `fmemopen` equivalent for wide chars
 - Make Cubically non-portable by writing the string to `/tmp/.cubically-input-(random string)`

**Comment by aaronryank** [comment]
https://stackoverflow.com/q/45624195/6850771

**Comment by TehPers** [comment]
[Is it possible to manually parse the input as bytes and convert it to UTF-8?](https://github.com/Cubically/cubically-lua/blob/codepage/codepage.lua#L60-L104)

**Comment by aaronryank** [comment]
Oh that's right, I fixed it. Bytes from Cubically's codepage must be present in the string as Cubically SBCS, not UTF-8.
