### ISSUE TITLE
What will turn commands look like for 4+ size cubes?

### ISSUE THREAD

**Issue by rexroni** [aaronryank/rubiks-cube#13]
I noticed while playing with a 4-size cube that the inner four cubelets never change, because the RUFetc instructions aren't really scalable outside of a 3x3x3 cube.

I don't think it is a critical issue right now, but I was curious if you had a plan for how to deal with that in the future?

**Comment by aaronryank** [comment]
Yes, we've been discussing this in the [Cubically chat room](https://chat.stackexchange.com/rooms/62883/cubically) for some time. If you check out [Cubically's code page](https://github.com/aaronryank/cubically/wiki/Code-page) you'll notice that the first 9 characters are Unicode superscript numbers. I plan on using these to turn inner layers of the cube.

For example, `R⁰2` will behave like `R2`. `R¹2` will turn the middle on a 3x3x3, and `R²2` will turn the middle on a 5x5x5 and the left face counterclockwise on a 3x3x3. Basically, a superscript character `x` after a turn command `y` will mean "Turn the `x`th layer inward from the `y`th face".

I had this all implemented up until a couple hours ago, when my system crashed. Now I'm dealing with a bunch of little bugs based on the state of the repo halfway through development. Fun stuff.

Should be implemented by next week.

**Comment by aaronryank** [comment]
[These have been implemented.](https://github.com/aaronryank/cubically/wiki/Inner-layer-turns)
