### ISSUE TITLE
Implicitly call command

### ISSUE THREAD

**Issue by TehPers** [aaronryank/rubiks-cube#2]
If a command requires no arguments, it'd be cleaner and shorter if the code could call the commands implicitly without needing arguments.

**Example**: `$%7` would load a number as input, then output that number to the screen. Currently, this must be accomplished with `$7%7`, even though the argument supplied to `$` doesn't matter and it will always load input to "face" 7 (the input "face"). `$7%7` would still behave identically to `$%7`, and `$77%7` would load input twice before outputting only the second input that was loaded.

**Comment by aaronryank** [comment]
I like the idea; trouble is, I'll have to modify the interpreter quite a bit to get it working.

As I'm currently in the middle of fixing a small bug with loops, and adding command blocks / jumps, this may sit on the backseat for a (little) while. I hope to have everything done by the end of the week.

**Comment by aaronryank** [comment]
Done, see latest commit.
