### ISSUE TITLE
If..Else bugged when nested

### ISSUE THREAD

**Issue by TehPers** [aaronryank/rubiks-cube#6]
The following code should print "27", however it prints "2745":
`?3{%3?0%4}!%5`

This is caused by the internal `?` failing and setting `if_else` to `0`. When this occurs, the `!` after the main conditional sees that `!` is `0` and executes.

**Comment by aaronryank** [comment]
Hmm, this didn't used to happen. I'll look into it.

**Comment by aaronryank** [comment]
Mostly fixed in the latest commit; I still need to think of a good way to reset `do_else` if the command after an `if` is skipped is not `else`.
