### ISSUE TITLE
Command that allows arguments to be passed from stdin?

### ISSUE THREAD

**Issue by rexroni** [aaronryank/rubiks-cube#9]
Why is there no way to specify the argument of any function from input?

For example, F1 always turns the front face 1, but there's no way to specify F(whatever-is-in-7).

You could add a dereference character, we'll say X, where FX7 is interpreted as F(whatever-is-in-7).  That would be more difficult, but more versatile.

I propose that you just add a new character that reads an argument from stdin, say: '#', so F# would read a 0-9 from stdin.

In fact I wrote a patch for this too, and I will submit the pull request shortly.

**Comment by aaronryank** [comment]
I mean, you can do this in a few bytes anyway if you know the state of the cube... this could be used in the place of `R#`:

    <get the cube solved>
    R3D1R1$:7(R1-0)6
    <get the cube back to original position>

**Comment by TehPers** [comment]
Pull request: #11

**Comment by aaronryank** [comment]
Here are some ways we've come up with that could do this (without messing with Cubically's existing syntax):

 - `R𝟐` (or `R𝟚`, or `R𝟤`, etc) would rotate the right face x times, where x is the value of face 2
 - `R` with a diacritic mark over it would act like `R`, except each argument passed to it would be a face index (rotate the right face x times, where x is the value of the face index) instead of a number of times to rotate the right face

**Comment by TehPers** [comment]
Is there anyway to rotate layer `x`?

**Comment by aaronryank** [comment]
Ok, so:

 - The double-struck numbers, [0x90 to 0x99](https://github.com/aaronryank/cubically/wiki/Code-page), when passed as arguments, mean 'take the argument from the face value of the index I represent'.
 - The superscript numbers, [0x00 to 0x09](https://github.com/aaronryank/cubically/wiki/Code-page), when passed as arguments, mean 'take the layer depth from the face value of the index I represent'.
 - The subscript numbers, [0x10 to 0x19](https://github.com/aaronryank/cubically/wiki/Code-page), are what superscript numbers used to do; they simply specify the depth of face turns.

**Comment by aaronryank** [comment]
@rexroni I added your original suggestion for `#` as `𝕀` in one the most recent commits.
